# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be06d5b4926d734cbb70d5cd49579afae5e1ba63e63eefa4e7754048a19486f3468ae09c307931ded92ed9bcfd5329cbeb5272f653d52bf69d714752fb8f18c

test:
  secret_key_base: b011502ca9c92beb4208398469fa2aad21b1150d11cc24fd029bd1548b9542cc87f72c6d5133becc6eabc4954af275bfa90f4d2e92b3f246d0e6e6ded0b17a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
